### ISSUE TITLE
EIP 155 doesn't define chainID

### ISSUE THREAD

**Issue by chaals** [eea-oasis/L2#36]
[[R4]](https://github.com/eea-oasis/L2/blob/main/workitems/tokenlist/l2-token-list-v1.0-psd01.md#r4) says
The chainId property MUST follow [EIP-155](https://github.com/eea-oasis/L2/blob/main/workitems/tokenlist/l2-token-list-v1.0-psd01.md#eip155) standard.

EIP 155 doesn't define chainID, just a way to use it.

Given that its proposal effectively defines a centralised registry as the answer to identifying chains, I suggest that [D2](https://github.com/eea-oasis/L2/blob/main/workitems/tokenlist/l2-token-list-v1.0-psd01.md#d2) (conforming to the proposed EIP3220) be upgraded to a MUST if the EIP is ready for use (and in the meantime noting the potential dependency and maybe working on that spec), and that instead R4 require registering unique chainIDs at https://github.com/ethereum-lists/chains 

Edited: I meant D2 not R5 (although changing the requirement level changes the identifier using the current scheme :( ).

**Comment by Therecanbeonlyone1969** [comment]
@chaals EIP3220 is a draft standard and could possibly change. One could argue it should not even be a D but an O or not even included at all.

Defining chainId beyond what is given in EIP155 and he associated lists is beyond the scope of the token list standard. Having said that, it is probably worthwhile creating a standard defining chainId overall.

**Comment by chaals** [comment]
yeah, right now EIP3220 isn't ready for use in this spec as a requirement as noted in my initial comment

>  if the EIP is ready for use (and in the meantime noting the potential dependency and maybe working on that spec)

On the other hand, EIP155 doesn't fit the purpose for which this spec is using it, since 155 doesn't require what's actually needed. The approach it follows, to rely on a github-based registry for uniqueness, has unfortunate implications for decentralisation. But it's what Ethereum has relied on so far so maybe it's good enough for your purposes.

**Comment by Therecanbeonlyone1969** [comment]
@chaals Good enough for sure ... and pushing decentralization, while desirable, is outside of the scope of the token list standard. Also, for the purposes of this spec, the totality of EIP155 is sufficient albeit the name and some of the requirements are not obvious in alignment with [R4].

As to uniqueness, the title says "EIP-155: Simple replay attack protection" and we have the following:
```
the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process.
```
In order to avoid a replay attack, the vs used in the signature generation must be different for each chain, therefore, each chainId must be different. This implies uniqueness but does not describe how to achieve uniqueness and uniqueness verification (can be done with a block explorer for example). I totally that this is an open issue that should be addressed.
